In [1]:
import numpy

In [2]:
import numpy as np

# Python list
#list comprehension
#array module(import lib array)
#numpy array:
   #zero
   #ones
   #full
   #eye
  #arrange
  #reshape
  #indexing

In [3]:
np.__version__

'1.26.4'

In [4]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [6]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [7]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [8]:
arr=np.arange(0,100)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [12]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [13]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [16]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l=[1,2,3,4,5]

In [4]:
l

[1, 2, 3, 4, 5]

In [5]:
# d/f b/w list and array
#list: It can store different types of data can be saved(Heterogeneous data save be saved).
#array:It can store only a single type of data

In [8]:
l2=[x for x in range(0,10)]

In [9]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
l3=[str(x) for x in l2]

In [11]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
l4=[x*x for x in range(0,10)]

In [13]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
l5=[x**2 for x in l2]

In [21]:
l5

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [16]:
import array

In [17]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

In [24]:
arr=array.array('i',l2)

In [25]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
type(arr)

array.array

In [30]:
arr1=array.array("i",[x**2 for x in l2])

In [34]:
import numpy as np

In [35]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [37]:
np.array([1,2,3,6],dtype='float')

array([1., 2., 3., 6.])

In [38]:
np.array([1,2,3,6],dtype='str')

array(['1', '2', '3', '6'], dtype='<U1')

In [40]:
np.array([1,2,3,6],dtype=np.float32)

array([1., 2., 3., 6.], dtype=float32)

In [42]:
l2d=[[1,2,3],[4,5,6]]

In [43]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [47]:
lc2d=[range(i,i+3) for i in [1,3]]

In [48]:
lc2d

[range(1, 4), range(3, 6)]

In [49]:
np.array(lc2d)

array([[1, 2, 3],
       [3, 4, 5]])

In [53]:
lc3d=[range(i,i+3) for i in [1,3,5]]

In [54]:
lc3d

[range(1, 4), range(3, 6), range(5, 8)]

In [55]:
np.array(lc3d)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [59]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [60]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.ones([1,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [66]:
arr=np.zeros([10,10])

In [67]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
arr[1:9,1:9]=1

In [71]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
arr[1:9,1:9]=9

In [75]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
arr[2:8,2:8]=8

In [77]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr[3:7,3:7]=7

In [79]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
arr[4:6,4:6]=6

In [81]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
arr[5:6,5:6]=5

In [85]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 5., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
a=np.ones([3,3])

In [95]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
#ar=np.arange(0,9,dtype='float'

In [97]:
np.full((3,4),(3.14))

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [98]:
np.full((3,4),('abc'))

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [101]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
np.transpose(np.eye(5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import numpy as np

In [5]:
np.full((6,6),(64))

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [6]:
#Linspace-Linaearly spaced elements:== It separates elements with same difference within a range: Example give below:
np.linspace(0,100,5)
#Here 0,100 is range and 5 is number of elemenst we want in return so menas we want 5 between 0 to 100 with equal difference and elements should be 5 

array([  0.,  25.,  50.,  75., 100.])

In [9]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001D8BFB57880>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The 

In [10]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [12]:
np.random? #random function can repeat the values

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\harsh shah\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\harsh shah\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy 

In [13]:
np.random.random((3,3))   # Here 1st random word denotes random module and second random denotes function and then value represnts the size of matrices and here it is always positive values returns

array([[0.05280065, 0.35360052, 0.91037507],
       [0.30482106, 0.20677409, 0.90926536],
       [0.99216315, 0.58444958, 0.18962058]])

In [14]:
np.random.random(3)

array([0.15361143, 0.10756728, 0.53796131])

In [15]:
np.random.random((2,2))

array([[0.95388202, 0.54790315],
       [0.38168683, 0.90443198]])

In [17]:
np.random.normal? 

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [18]:
np.random.normal(0,1,10) # Here random.noraml also returns negative values in such a way that mean of that numbers is always come as 0 and std dev of that numbers is always come as 1.

array([ 1.01667611, -0.30792283,  0.12411958,  0.39158109, -0.84414711,
        1.68771082, -0.88538298, -0.15788412,  0.56304845,  1.616798  ])

In [26]:
np.random.normal(0,1,(2,2))

array([[ 0.22705193,  1.63439295],
       [ 0.3658269 , -1.32419177]])

In [24]:
np.random.seed?

Docstring:
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator
Type:      builtin_function_or_method

In [31]:
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335])

In [32]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [34]:
np.random.randint(0,100,36)

array([11, 54, 88, 62, 33, 72, 78, 49, 51, 54, 77, 69, 13, 25, 13, 92, 86,
       30, 30, 89, 12, 65, 31, 57, 36, 27, 18, 93, 77, 22, 23, 94, 11, 28,
       74, 88])

In [35]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [36]:
np.random.randn  #Here in np.random.randn there is always mean of given numbers is 0 and variance of given numbers is 1


<function RandomState.randn>

In [37]:
#Opaerations on numpy array

In [48]:
arr=np.random.randint(0,100,(2,3))

In [49]:
arr

array([[40, 89, 73],
       [37,  0, 18]])

In [50]:
arr.ndim  # This function denotes number of dimensions

2

In [51]:
arr.size

6

In [52]:
arr.shape

(2, 3)

In [53]:
arr.dtype

dtype('int32')

array indexing 

In [55]:
arr1 = np.random.randint(0,40,10)

In [56]:
arr1

array([23,  3, 29, 16, 20, 18, 14, 15, 17, 25])

In [57]:
arr1[0]

23

In [58]:
arr1[4]

20

In [59]:
arr1[-1]

25

In [62]:
arr1[:4]

array([23,  3, 29, 16])

In [63]:
arr1[4:]

array([20, 18, 14, 15, 17, 25])

In [64]:
arr1[4:-2]

array([20, 18, 14, 15])

In [67]:
arr1[5]=15

In [68]:
arr1

array([23,  3, 29, 16, 20, 15, 14, 15, 17, 25])

In [110]:
a1=np.arange(1,2).reshape(1)
a1

array([1])

In [99]:
a2=np.arange(0,4).reshape(2,2)
a2

array([[0, 1],
       [2, 3]])

In [114]:
a3=np.arange(0,27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a1.dtype

dtype('int32')

In [102]:
a2.dtype

dtype('int32')

In [103]:
a3.dtype

dtype('int32')

In [104]:
a1.shape

(1, 1)

In [105]:
a2.shape

(2, 2)

In [106]:
a3.shape

(3, 3)

In [115]:
a1.ndim

1

In [116]:
a2.ndim

2

In [117]:
a3.ndim

3

In [118]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(0,40,10)

In [4]:
arr1

array([ 2, 23, 15, 30, 27, 18,  6, 10,  2, 10])

In [5]:
arr1[2:6:2]

array([15, 27])

In [6]:
arr1[::2]

array([ 2, 15, 27,  6,  2])

In [7]:
# Print array in reverse
arr1[::-1]

array([10,  2, 10,  6, 18, 27, 30, 15, 23,  2])

In [8]:
arr1[::-2]

array([10, 10, 18, 30, 23])

In [19]:
arr2=np.arange(0,25).reshape(5,5)

In [20]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr2[0,1:4]

array([1, 2, 3])

In [23]:
arr2[0,1]

1

In [25]:
arr2[2,1]

11

In [26]:
arr2[3,3]

18

In [27]:
arr2[2,4]

14

In [31]:
arr2[0:3,1]

array([ 1,  6, 11])

In [32]:
arr2[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [33]:
arr2[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [35]:
arr2[2:4,3:5]

array([[13, 14],
       [18, 19]])

In [36]:
arr2[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [38]:
arr2[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [39]:
arr2[::1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr2[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [41]:
arr2[::,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [42]:
arr2[::-1,::]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [43]:
arr2[::-1,::-1]

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [1]:
import numpy as np

In [4]:
Checkerboard=np.zeros([8,8])

In [5]:
Checkerboard

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
a=np.arange(0,9).reshape(3,3)

In [18]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [20]:
sa=a[1:3,1:3]

In [21]:
sa

array([[4, 5],
       [7, 8]])

In [24]:
sa[1,1]=19

In [25]:
sa

array([[ 4,  5],
       [ 7, 19]])

In [26]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 19]])

In [55]:
a[1,2]=16

In [56]:
a

array([[ 0,  1,  2],
       [ 3,  4, 16],
       [ 6,  7, 16]])

In [64]:
a[2,1]=7
a

array([[ 0,  1,  2],
       [ 3,  4, 16],
       [ 6,  7, 16]])

In [66]:
a[2,2]=19
a

array([[ 0,  1,  2],
       [ 3,  4, 16],
       [ 6,  7, 19]])

In [67]:
#deep copy
da=a[:2,:2].copy()
da

array([[0, 1],
       [3, 4]])

In [68]:
da[1,1]

4

In [69]:
da[1,1]=15

In [70]:
da

array([[ 0,  1],
       [ 3, 15]])

In [71]:
a

array([[ 0,  1,  2],
       [ 3,  4, 16],
       [ 6,  7, 19]])

In [83]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [85]:
ar.reshape(3,1)

array([[1],
       [2],
       [3]])

In [81]:
A=np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [90]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
ar.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [92]:
ar.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [93]:
ar.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
ar.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
ar.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [96]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
ar1=ar.flatten()
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
ar1[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

#Concatenation, Joining of two arrays , Adiition

In [103]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

In [104]:
np.concatenate([sa,da])

array([[ 4, 16],
       [ 7, 19],
       [ 0,  1],
       [ 3, 15]])

In [107]:
ca=np.concatenate([sa,da],axis=1) # Axis is used to specify row or column , for row 0 amd for column 1
ca

array([[ 4, 16,  0,  1],
       [ 7, 19,  3, 15]])

In [109]:
a1=np.array([[1,1,1,1]])
a1

array([[1, 1, 1, 1]])

In [110]:
np.concatenate([ca,a1])   # if we concate in row then number of column must be equal simikarly if we concate in column then number of row must be equal

array([[ 4, 16,  0,  1],
       [ 7, 19,  3, 15],
       [ 1,  1,  1,  1]])

In [2]:
import numpy as np

In [5]:
list=[12345,"Diksha","Dikshar@nuc.ac.in"]

In [6]:
list

[12345, 'Diksha', 'Dikshar@nuc.ac.in']

In [9]:
list=[45667,"Jiva","Jiva@nuc.ac.in"]
list

[45667, 'Jiva', 'Jiva@nuc.ac.in']

In [14]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [52]:
ar=np.zeros([10,10])
ar[::2,::2]=1
ar[1::2,1::2]=1
ar

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [43]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x00000204B99C7240>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

``np.row_stack`` is an alias for `vstack`. They are the same function.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first a

In [45]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])

In [46]:
#Stcak arrays in sequence vertically (row wise)
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [47]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [49]:
ar=np.array([[1,3],
             [4,5]])
ar

array([[1, 3],
       [4, 5]])

In [54]:
x,grid[:,np.newaxis]

(array([1, 2, 3]),
 array([[[9, 8, 7]],
 
        [[6, 5, 4]]]))

In [55]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [56]:
x

array([1, 2, 3])

In [57]:
#In slpit there are two arguemnets we have pass 1st range and 2nd number of parts in which we have to split
# np.split
#np.vsplit   In vsplit it will split  row wise
#np.hsplit   In hsplit it will split column wise

In [59]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x00000204B9B249A0>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned corr

In [62]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
np.split(arr,10)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [65]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x00000204B9B24B80>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[

In [68]:
ar1=np.arange(0,36).reshape(6,6)

In [69]:
ar1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
np.vsplit(ar1,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [72]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [75]:
np.split(a,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [76]:
np.split(a,[2,3])  # here 2,3 are index numebr

[array([1, 2]), array([3]), array([4, 5])]

In [78]:
np.split(a,[1,2,4]) #here 1,2,4 are index number 

[array([1]), array([2]), array([3, 4]), array([5])]

In [81]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.vsplit(ar,[1,2])

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [89]:
np.hsplit(ar,[1,2])

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [90]:
np.abs(-5)

5

#Concatenate
hstack
vstcak
split
hsplit
vsplit
aggregation

In [91]:
a

array([1, 2, 3, 4, 5])

In [92]:
np.sum(a)

15

In [93]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.sum(ar)

36

In [95]:
np.sum(ar,axis=0)  # here axix = 0 means it will give sum column wise

array([ 9, 12, 15])

In [96]:
np.sum(ar,axis=1) # here axis = 1 means it will give sum row wise

array([ 3, 12, 21])

In [97]:
np.min(a)

1

In [98]:
np.max(a)

5

In [99]:
np.argmax(a)  # min or max will give min or max number wise which are present in range and argmax or argmin will give min or max index wise

4

In [112]:
np.max(ar,axis=0)

array([6, 7, 8])

In [114]:
np.min(ar,axis=1)

array([0, 3, 6])

In [100]:
np.argmin(a)

0

In [101]:
i=-4

In [102]:
np.abs(i)

4

In [103]:
np.absolute(i)

4

In [104]:
np.mean(a)

3.0

In [106]:
np.var(a)

2.0

In [107]:
np.std(a)

1.4142135623730951

In [108]:
np.median(a)

3.0

In [109]:
np.product(a)   # Product will return factorial

120

In [113]:
np.argmax(ar)

8

In [8]:
import numpy as np

In [9]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000025714B84E00>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[

In [10]:
np.floor?

Call signature:  np.floor(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'floor'>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the floor of the input, element-wise.

The floor of the scalar `x` is the largest integer `i`, such that
`i <= x`.  It is often denoted as :math:`\lfloor x \rfloor`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is

In [13]:
np.ceil?

Call signature:  np.ceil(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'ceil'>
File:            c:\users\harsh shah\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
``i >= x``.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is 

In [14]:
np.ceil(13.5)

14.0

In [16]:
np.floor(13.5)

13.0

In [21]:
a=np.arange(0,5)
a
b=np.full(5,5)
print(a,b)

[0 1 2 3 4] [5 5 5 5 5]


In [22]:
a+b

array([5, 6, 7, 8, 9])

In [23]:
c=np.full(2,3)[:,np.newaxis]

In [24]:
c

array([[3],
       [3]])

In [25]:
b+c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [37]:
m=np.full(2,3)
n=np.full(2,1)[:,np.newaxis]
s=m+n
print(n)
display(m+n,   s)
display(s+5)


[[1]
 [1]]


array([[4, 4],
       [4, 4]])

array([[4, 4],
       [4, 4]])

array([[9, 9],
       [9, 9]])

In [41]:
o=np.ones((3,3))
a=np.arange(3)
display(o,a)
display(o+a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [42]:
a>1

array([False, False,  True])

In [43]:
a==0

array([ True, False, False])

In [44]:
a<1

array([ True, False, False])

In [45]:
a<-1

array([False, False, False])

# NUMPY EXERCISE 1

In [3]:
#[1] Import Numpy as np
import numpy as np

In [5]:
#[2] Create an array of 10 zeros
a=np.zeros([10])
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#[3] Create an array of 10 ones
b=np.ones([10])
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#[4] Craete an array of integer 10 to 50
c=np.arange(10,51)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
#[5] Create an array of all the even integers from 10 to 50
d=np.arange(10,51,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
#[6] Create a 3x3 matrix with values ranging from 0 to 8 
e=np.arange(0,9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
#[7] Create a 3x3 identity matrix
f=np.eye(3,3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#[8] Use numpy to generate a random number between 0 to 1
g=np.random.random(1)
g

array([0.02804727])

In [40]:
#[9] Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution
h=np.random.normal(0,1,25)
h

array([-1.02787909,  0.92509816,  0.49543471,  0.43446148, -1.05607013,
        0.32960982,  0.10658691, -2.4623284 , -0.8720728 ,  1.67284273,
       -0.34702225, -0.43876237, -0.3633552 , -1.42114572,  0.9637164 ,
        0.14713313,  0.08072669, -0.71571365, -0.66298858,  1.01598886,
       -0.69215246,  0.16292622, -1.05330179, -0.54703755, -0.15836861])

In [44]:
#[10] Create a matrix of 10x10 matrix of lineraly spaced elements from 0.01 to 1
i=np.linspace(0.01,1,100).reshape(10,10)
i

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [46]:
#[11] Create an array of 20 lineraly spaced points between 0 and 1
j=np.linspace(0,1,20)
j

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [47]:
#[12] Create an 5x5 matrix from 1 to 25
k=np.arange(1,26).reshape(5,5)
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
#[12a] Find following using slicing
k[2:5,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [56]:
#[12b] find 20 in the matrix
k[3,4]

20

In [67]:
#[12c] find 2 from the matrix
k[0:3,1,np.newaxis]

array([[ 2],
       [ 7],
       [12]])

In [68]:
#[12d] find array 21 to 25 from the matrix
k[4,:5]

array([21, 22, 23, 24, 25])

In [70]:
k[3:5,:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
#[13] Get Sum of all values in matrix
np.sum(k)

325

In [76]:
#[14] Get sum of all the columns in matrix
np.sum(k,axis=0)

array([55, 60, 65, 70, 75])

In [80]:
#[15] Get standard deviation, variance , minimum,maximum from matrix row-wise
np.std(k,axis=1)


array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [81]:
np.var(k,axis=1)

array([2., 2., 2., 2., 2.])

In [82]:
np.min(k,axis=1)

array([ 1,  6, 11, 16, 21])

In [83]:
np.max(k,axis=1)

array([ 5, 10, 15, 20, 25])

In [126]:
#[16] Create 2D matrix with all border values nan
m=np.full((4,4),np.nan)
m

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [127]:
m[1:3,1:3]=0

In [128]:
m

array([[nan, nan, nan, nan],
       [nan,  0.,  0., nan],
       [nan,  0.,  0., nan],
       [nan, nan, nan, nan]])

# NUMPY EXERCISE 2

In [129]:
#[1] Create 1D,2D,3D numpy array
a1=np.arange(1,2).reshape(1)
a1


array([1])

In [130]:
a2=np.arange(0,4).reshape(2,2)
a2


array([[0, 1],
       [2, 3]])

In [131]:
a3=np.arange(0,27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
#[2] Print data type of array
a1.dtype

dtype('int32')

In [133]:
a2.dtype

dtype('int32')

In [134]:
a3.dtype

dtype('int32')

In [140]:
#[3] Print shape and dimensions of all the three different array
a1.shape

(1,)

In [141]:
a2.shape

(2, 2)

In [142]:
a3.shape

(3, 3, 3)

In [143]:
a1.ndim

1

In [145]:
a2.ndim

2

In [146]:
a3.ndim

3

In [147]:
#[4] Create another 1D array of 12 elemenrs filled with zero
a=np.zeros(12)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [150]:
#[5] Create another 2D array elements filled with ones 
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [155]:
#[6] Creaye a 1D array known as Maths Marks out of 100 having 20 elements
c=np.random.randint(0,100,20)
c

array([77, 26, 35, 40, 99, 66, 93, 43, 64, 68, 99, 60, 43, 80, 72, 76, 19,
       42, 56, 89])

In [157]:
#[7] Sort the above array in ascending and descending
d=np.sort(c)
d

array([19, 26, 35, 40, 42, 43, 43, 56, 60, 64, 66, 68, 72, 76, 77, 80, 89,
       93, 99, 99])

In [161]:
e=np.sort(c)[::-1]
e

array([99, 99, 93, 89, 80, 77, 76, 72, 68, 66, 64, 60, 56, 43, 43, 42, 40,
       35, 26, 19])

In [163]:
#[8] Create a copy of sorted array to another variable by deep copying
f=e[::].copy()
f

array([99, 99, 93, 89, 80, 77, 76, 72, 68, 66, 64, 60, 56, 43, 43, 42, 40,
       35, 26, 19])

In [166]:
#[9] Create 2D array of 5x5 which is an identity matrix and then convert 1D
g=np.eye(5,5)
g

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [169]:
g.reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [170]:
#[10] Create 2D array 3x3. Add one more row to it
h=np.arange(0,9).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
i=np.arange(9,12).reshape(1,3)
i

array([[ 9, 10, 11]])

In [180]:
j=np.concatenate([h,i])
j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [193]:
#[11] Split above array created vertically and horizontally
k=np.vsplit(j,4)
k

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [192]:
m=np.hsplit(j,3)
m

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [196]:
#[12] Create 4x4 identity matrix. Add 4 to each element
n=np.eye(4,4)
n

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [198]:
o=4
p=o+n
p

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [202]:
#[13] Create 1D array. Initialize with floating point values. Display its ceil,floor and round(with 2 decimals)
x=np.random.random(5)
x

array([0.04666371, 0.8309085 , 0.32439289, 0.28642438, 0.87229602])

In [211]:
r=np.ceil(x)
r

array([1., 1., 1., 1., 1.])

In [206]:
t=np.round(x,2)
t

array([0.05, 0.83, 0.32, 0.29, 0.87])

In [209]:
s=np.floor(x)
s

array([0., 0., 0., 0., 0.])

In [213]:
#[14] Create 5x5 matrix. Display min,max,variance, standard deviation column-wise
y=np.arange(5,30).reshape(5,5)
y

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [214]:
np.min(y,axis=0)

array([5, 6, 7, 8, 9])

In [216]:
np.max(y,axis=0)

array([25, 26, 27, 28, 29])

In [217]:
np.var(y,axis=0)

array([50., 50., 50., 50., 50.])

In [218]:
np.std(y,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [220]:
#[15] Create a null vector of size 10 with 6th value filled with 200
z=np.full((10),(np.nan))
z

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [222]:
z[5]=200
z

array([ nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan,  nan])

In [223]:
#[16] Craete a 1D array/vector with values ranging fromm 100 to 150 in sequence
u=np.arange(100,151)
u

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [230]:
#[17] Reverse the above vector
u[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [4]:
import numpy as np

In [5]:
#[18] Create a 5x5 matrix with values ranging from 0-24 using some function
v=np.arange(0,25).reshape(5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
#[19] Find indices of non-zero elements from[1,0,2,0,0,4,0,8]
e=np.array([1,0,2,0,0,4,0,8])
e


array([1, 0, 2, 0, 0, 4, 0, 8])

In [44]:
f=np.nonzero(e)
f

(array([0, 2, 5, 7], dtype=int64),)

In [45]:
#[20] Create a 10x10 matrix with 1 on the borders and 0 inside
q=np.ones(100).reshape(10,10)
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
q[1:9,1:9]=0
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
#[21] Create 8x8 matrix and fill with 1 and 0 in checkboard pattern
o=np.zeros([8,8])
o

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
o[::2,::2]=1
o[1::2,1::2]=1
o

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [31]:
#[22] Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
x=np.random.randint(1,20,[3,3])
x

array([[ 5,  9, 12],
       [19,  6,  9],
       [17, 18,  8]])

In [34]:
y=np.random.randint(21,40,[3,3])
y

array([[33, 24, 22],
       [37, 28, 25],
       [22, 31, 24]])

In [36]:
z=x+y
z

array([[38, 33, 34],
       [56, 34, 34],
       [39, 49, 32]])

In [37]:
a=x-y
a

array([[-28, -15, -10],
       [-18, -22, -16],
       [ -5, -13, -16]])

In [38]:
b=x*y
b

array([[165, 216, 264],
       [703, 168, 225],
       [374, 558, 192]])